language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=latest
    - php: 7.0
      env:
        - DEPS=lowest
    - php: 7.0
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=latest
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=latest
  allow_failures:
    - php: 7.2

before_install:
  - travis_retry composer self-update

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - (cd tests ; ../vendor/bin/phpunit ./)

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml